<MyRoot>:

    orientation: 'vertical'

    calc_field: calc_field
    TextInput:
        id: calc_field
        height: 100
        size_hint: (1, None)
        readonly: True
        disabled: True
        font_size: 64

    GridLayout:
        rows: 4
        cols: 4
        padding: 10
        spacing: 10
        height: 400
        size_hint: (1, None)
        Button:
            text: "1"
            font_size: 26
            on_press: root.calc_symbol('1')
        Button:
            text: "2"
            font_size: 26
            on_press: root.calc_symbol('2')
        Button:
            text: "3"
            font_size: 26
            on_press: root.calc_symbol('3')
        Button:
            text: "+"
            font_size: 26
            on_press: root.calc_symbol('+')
            background_color: 0.5, 0.5, 0.5, 1 #Grey Color
        Button:
            text: "4"
            font_size: 26
            on_press: root.calc_symbol('4')
        Button:
            text: "5"
            font_size: 26
            on_press: root.calc_symbol('5')
        Button:
            text: "6"
            font_size: 26
            on_press: root.calc_symbol('6')
        Button:
            text: "-"
            font_size: 26
            on_press: root.calc_symbol('-')
            background_color: 0.5, 0.5, 0.5, 1
        Button:
            text: "7"
            font_size: 26
            on_press: root.calc_symbol('7')
        Button:
            text: "8"
            font_size: 26
            on_press: root.calc_symbol('8')
        Button:
            text: "9"
            font_size: 26
            on_press: root.calc_symbol('9')
        Button:
            text: "x"
            font_size: 26
            on_press: root.calc_symbol('*')
            background_color: 0.5, 0.5, 0.5, 1
        Button:
            text: "("
            font_size: 26
            on_press: root.calc_symbol('(')
        Button:
            text: "0"
            font_size: 26
            on_press: root.calc_symbol('0')
        Button:
            text: ")"
            font_size: 26
            on_press: root.calc_symbol(')')
        Button:
            text: "÷"
            font_size: 26
            on_press: root.calc_symbol('/')
            background_color: 0.5, 0.5, 0.5, 1

    GridLayout:
        rows: 1
        cols: 4
        padding: 10
        spacing: 10
        height: 110
        size_hint: (1, None)

        Button:
            text: "^2"
            on_press: root.calc_symbol('**2')
            font_size: 26
        Button:
            text: "^3"
            on_press: root.calc_symbol('**3')
            font_size: 26
        Button:
            text: "^4"
            on_press: root.calc_symbol('**4')
            font_size: 26
        Button:
            text: "^5"
            on_press: root.calc_symbol('**5')
            font_size: 26
            background_color:

    BoxLayout:
        orientation: 'horizontal'
        padding: 7
        spacing: 7
        height: 100
        size_hint: (1, None)

        Button:
            text: "Clear"
            font_size: 26
            background_color: 1, 0.5, 0, 1 #orange color
            on_press: root.clear()
        Button:
            text: "."
            font_size: 26
            on_press: root.calc_symbol('.')
        Button:
            text: "="
            font_size: 26
            background_color: 0, 0.5, 1, 1  #blue color
            on_press: root.get_result()
